-- 코드를 입력하세요

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY, sum(TOTAL_SALES)
FROM
    (SELECT BOOK_SALES.SALES_DATE, AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, sales*price AS TOTAL_SALES
    FROM BOOK_SALES 
    JOIN BOOK ON BOOK_SALES.book_id = BOOK.book_id 
    JOIN AUTHOR on AUTHOR.author_id = BOOK.author_id
    WHERE (YEAR(BOOK_SALES.SALES_DATE)=2022 AND MONTH(BOOK_SALES.SALES_DATE)=01)) A
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY
ORDER bY AUTHOR_ID, CATEGORY DESC;