SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_D, 
        PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE SALES_DATE LIKE '%2022-03%'
UNION ALL
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_D,
        PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE SALES_DATE LIKE '%2022-03%'
ORDER BY SALES_D ASC, PRODUCT_ID ASC, USER_ID ASC;