SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM (SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES, rank() over (PARTITION BY food_type ORDER BY favorites desc) as r
FROM REST_INFO
ORDER BY FOOD_TYPE) A
WHERE r = 1
ORDER BY FOOD_TYPE DESC;