-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) as addr,
       CONCAT_WS('-',SUBSTR(TLNO, 1,3),SUBSTR(TLNO, 4,4),SUBSTR(TLNO, 8,4)) as TEL
FROM
    (SELECT WRITER_ID, count(*) cnt
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING cnt>=3) A
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
ORDER BY USER_ID desc;