-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT_F FROM FIRST_HALF
     GROUP BY FLAVOR) A
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOT_J FROM JULY
    GROUP BY FLAVOR) B
ON A.FLAVOR = B.FLAVOR
ORDER BY TOT_F+TOT_J DESC
LIMIT 3;