
SELECT MONTH(START_DATE) AS MON, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE MONTH(START_DATE) BETWEEN 8 AND 10
               GROUP BY CAR_ID
               HAVING COUNT(*) >=5) 
AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MON, CAR_ID
ORDER BY MON ASC, CAR_ID DESC;